/**
 * The shape of `public/retro/manifest.json` (generated by retro/build.ts) plus
 * the one rule that decides whether a row is runnable.
 *
 * This module exists so the Norton Commander island and the deep-link route
 * (`/{locale}/lab/retro-games/{DIR}/{FILE}/`) agree by construction: a link is
 * generated for exactly the rows the panel shows as runnable, because both call
 * the SAME function. It was briefly duplicated in the two files, which is the
 * kind of copy that stays correct right up until a port is added.
 *
 * Keep this module free of Node built-ins — the island bundles it for the
 * browser. Reading the file off disk is the route's job.
 */

/** A UI string in both site locales. */
export interface LocStr {
  en: string;
  ua: string;
}

export interface ManifestFile {
  name: string;
  size: number;
  mtime: string;
  view: boolean;
}

export interface ManifestFolder {
  dir: string;
  title: string;
  year: string;
  note: LocStr;
  controls?: LocStr;
  run?: string; // folder default (F6 / any .EXE)
  runs?: Record<string, string>; // specific file → its own port slug
  files: ManifestFile[];
}

export interface Manifest {
  generatedAt: string;
  folders: ManifestFolder[];
}

/**
 * The port slug this specific file would launch: an explicit `runs` mapping
 * wins, else the folder default applies only to a .EXE. Returns undefined for
 * every non-runnable row (sources, data, the dimmed binaries).
 */
export function runSlugFor(folder: ManifestFolder, file: { name: string }): string | undefined {
  return folder.runs?.[file.name] ?? (/\.exe$/i.test(file.name) ? folder.run : undefined);
}
